#!/bin/bash

# Setup dev environment

# get dir of script (ie: the project root)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# 1. create db
rm -rf "$DIR/gomarks.db"
sqlite3 "$DIR/gomarks.db" <<EOF
CREATE TABLE user (id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, active INTEGER NOT NULL);
CREATE TABLE mark (id INTEGER PRIMARY KEY, title TEXT, url TEXT, user_id INTEGER NOT NULL, FOREIGN KEY(user_id) REFERENCES user(id));
INSERT INTO user (email, password_hash, active) VALUES ('test@example.com', '\$2a\$14\$RjtUXdY343NfD2xpp/2GguI/3wK5tlLguKh/mtRgdFwfyu7jWfgUy', 1);
INSERT INTO mark (title, url, user_id) VALUES ('Google', 'https://google.com', 1), ('Amazon', 'https://amazon.com', 1);
EOF

# 2. create .env file
cat > "$DIR/.env" <<EOF
GOMARKS_SECRET=secret
GOMARKS_DB=gomarks.db
EOF
